name: Documentation Label
on:
  project_card:
    - moved

jobs:
  update_label:
    if: github.event.project_card.column_id == 'In Review'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
        with:
          script: |
            // this gets the number at the end of the content URL, which should be the issue/PR number
            const issue_num = context.payload.project_card.content_url.split('/').pop()
            github.rest.issues.addLabels({
              issue_number: issue_num,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["needs review"]
            })

