name: test_flow

on:
  project_card:
    types: [created]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["needs review"]
            })

