name: Needs Review Label
on:
  project_card:
    types: 
    - moved

jobs:
  update_label:
    if: github.event.project_card.column.name == 'In review'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["needs review"]
            })

