name: test_flow

on:
  project_card:
    types: [created]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
     - name: add bug label
       run: |
          gh issue edit --add-label "test"

