name: test_flow

on:
  issues:
    types:
      - created

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
     - name: add bug label
       run: |
          gh issue edit --add-label "test"

